### ISSUE TITLE
[Feature Request] - Copy Output After Translated

### ISSUE THREAD

**Issue by CyRamos** [cenyG/flow-launch-translate-plugin#3]
Hey
I'd like to request a feature. 
In the Calculator plugin, there is an option for copying the output (attach example)
I'd like to ask for the same feature here, I think it will be very efficient for a translation plugin. 
Hope it will be considered - many thanks ahead🥇 

![image](https://user-images.githubusercontent.com/40651473/197422943-2b0115e7-51e2-4a80-9d97-2c87353b49b0.png)

**Comment by cenyG** [comment]
@CyRamos 
Yeap, thought about it.
Actualy made a patch already, so it's now works for me, you can try it too
