### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by joseehilton147** [cenyG/flow-launch-translate-plugin#9]
![image](https://user-images.githubusercontent.com/53986027/222147339-105acaf7-d2d0-42bb-abf0-043df2261437.png)

just installed and the plugin didnt work, im doing something wrong?

**Comment by cenyG** [comment]
Yes, thank you.
There was an issue because of last MR with updating to new version of flowlauncher, I fix it in 1.0.2 version of plugin, it should work now
